[package]
name = "pgen"
version = "0.0.1"
authors = ["Leonardo Rossetti <me@lrossetti.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
rand = "0.7.3"
clap = "2.33.0"